/*
 * Reserver Api
 *
 * Room and ambulance reservation management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xhozza@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

 package reserver

import (
   "net/http"

   "github.com/gin-gonic/gin"
)

type RoomReservationAPI interface {

   // internal registration of api routes
   addRoutes(routerGroup *gin.RouterGroup)

    // CreateReservation - Create new reservation
   CreateReservation(ctx *gin.Context)

    // DeleteReservation - Delete reservation
   DeleteReservation(ctx *gin.Context)

    // GetReservationById - Provides the reservation by id
   GetReservationById(ctx *gin.Context)

    // GetReservations - Provides the list of current reservations
   GetReservations(ctx *gin.Context)

    // GetRooms - Provides the list of all rooms
   GetRooms(ctx *gin.Context)

    // UpdateReservation - Update reservation
   UpdateReservation(ctx *gin.Context)

 }

// partial implementation of RoomReservationAPI - all functions must be implemented in add on files
type implRoomReservationAPI struct {

}

func newRoomReservationAPI() RoomReservationAPI {
  return &implRoomReservationAPI{}
}

func (this *implRoomReservationAPI) addRoutes(routerGroup *gin.RouterGroup) {
  routerGroup.Handle( http.MethodPost, "/reservation", this.CreateReservation)
  routerGroup.Handle( http.MethodDelete, "/reservation/:id", this.DeleteReservation)
  routerGroup.Handle( http.MethodGet, "/reservation/:id", this.GetReservationById)
  routerGroup.Handle( http.MethodGet, "/reservation", this.GetReservations)
  routerGroup.Handle( http.MethodGet, "/rooms", this.GetRooms)
  routerGroup.Handle( http.MethodPut, "/reservation/:id", this.UpdateReservation)
}

// Copy following section to separate file, uncomment, and implement accordingly
// // CreateReservation - Create new reservation
// func (this *implRoomReservationAPI) CreateReservation(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // DeleteReservation - Delete reservation
// func (this *implRoomReservationAPI) DeleteReservation(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // GetReservationById - Provides the reservation by id
// func (this *implRoomReservationAPI) GetReservationById(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // GetReservations - Provides the list of current reservations
// func (this *implRoomReservationAPI) GetReservations(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // GetRooms - Provides the list of all rooms
// func (this *implRoomReservationAPI) GetRooms(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // UpdateReservation - Update reservation
// func (this *implRoomReservationAPI) UpdateReservation(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
