/*
 * Reserver Api
 *
 * Room and ambulance reservation management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xhozza@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package reserver

type Doctor struct {

	// Unique identifier of the department
	Id string `json:"id"`

	// Name of the hospital department
	Name string `json:"name"`

	// ID of their department
	Department string `json:"department"`
}
