/*
 * Reserver Api
 *
 * Room and ambulance reservation management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xhozza@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package reserver

import (
    "github.com/gin-gonic/gin"
)

func AddRoutes(engine *gin.Engine) {
  group := engine.Group("/api")
  
  {
    api := newDepartmentsAPI()
    api.addRoutes(group)
  }
  
  {
    api := newExaminationReservationAPI()
    api.addRoutes(group)
  }
  
  {
    api := newRoomReservationAPI()
    api.addRoutes(group)
  }
  
}