apiVersion: apps/v1
kind: Deployment
metadata:
  name: reserver-webapi
spec:
  template:
   spec:
      initContainers:
        - name: init-mongodb
          env:
            - name: RESERVER_API_MONGODB_HOST
              value: null
              valueFrom:
                configMapKeyRef:
                  name: mongodb-connection
                  key: host
            - name: RESERVER_API_MONGODB_PORT
              value: null
              valueFrom:
                configMapKeyRef:
                  name: mongodb-connection
                  key: port
            - name: RESERVER_API_MONGODB_USERNAME
              value: null
              valueFrom:
                secretKeyRef:
                  name: mongodb-auth
                  key: username
            - name: RESERVER_API_MONGODB_PASSWORD
              value: null
              valueFrom:
                secretKeyRef:
                  name: mongodb-auth
                  key: password
      containers:
        - name: reserver-webapi-container
          env:
            - name: RESERVER_API_MONGODB_HOST
              value: null
              valueFrom:
                configMapKeyRef:
                  name: mongodb-connection
                  key: host
            - name: RESERVER_API_MONGODB_PORT
              value: null
              valueFrom:
                configMapKeyRef:
                  name: mongodb-connection
                  key: port
            - name: RESERVER_API_MONGODB_USERNAME
              value: null
              valueFrom:
                secretKeyRef:
                  name: mongodb-auth
                  key: username
            - name: RESERVER_API_MONGODB_PASSWORD
              value: null
              valueFrom:
                secretKeyRef:
                  name: mongodb-auth
                  key: password